/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPartyRouteImport } from './routes/app.party'
import { Route as AppClassicRouteImport } from './routes/app.classic'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPartyRoute = AppPartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => AppRoute,
} as any)
const AppClassicRoute = AppClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/party': typeof AppPartyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/party': typeof AppPartyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/party': typeof AppPartyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/classic' | '/app/party'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app' | '/app/classic' | '/app/party'
  id: '__root__' | '/' | '/app' | '/app/classic' | '/app/party'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/party': {
      id: '/app/party'
      path: '/party'
      fullPath: '/app/party'
      preLoaderRoute: typeof AppPartyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classic': {
      id: '/app/classic'
      path: '/classic'
      fullPath: '/app/classic'
      preLoaderRoute: typeof AppClassicRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClassicRoute: typeof AppClassicRoute
  AppPartyRoute: typeof AppPartyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassicRoute: AppClassicRoute,
  AppPartyRoute: AppPartyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
