/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomNewRouteImport } from './routes/custom.new'
import { Route as CustomIdRouteImport } from './routes/custom.$id'
import { Route as AppProRouteImport } from './routes/app.pro'
import { Route as AppPartyRouteImport } from './routes/app.party'
import { Route as AppCustomRouteImport } from './routes/app.custom'
import { Route as AppClassicRouteImport } from './routes/app.classic'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomNewRoute = CustomNewRouteImport.update({
  id: '/custom/new',
  path: '/custom/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomIdRoute = CustomIdRouteImport.update({
  id: '/custom/$id',
  path: '/custom/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProRoute = AppProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AppRoute,
} as any)
const AppPartyRoute = AppPartyRouteImport.update({
  id: '/party',
  path: '/party',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomRoute = AppCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => AppRoute,
} as any)
const AppClassicRoute = AppClassicRouteImport.update({
  id: '/classic',
  path: '/classic',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/custom': typeof AppCustomRoute
  '/app/party': typeof AppPartyRoute
  '/app/pro': typeof AppProRoute
  '/custom/$id': typeof CustomIdRoute
  '/custom/new': typeof CustomNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/custom': typeof AppCustomRoute
  '/app/party': typeof AppPartyRoute
  '/app/pro': typeof AppProRoute
  '/custom/$id': typeof CustomIdRoute
  '/custom/new': typeof CustomNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/classic': typeof AppClassicRoute
  '/app/custom': typeof AppCustomRoute
  '/app/party': typeof AppPartyRoute
  '/app/pro': typeof AppProRoute
  '/custom/$id': typeof CustomIdRoute
  '/custom/new': typeof CustomNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/classic'
    | '/app/custom'
    | '/app/party'
    | '/app/pro'
    | '/custom/$id'
    | '/custom/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/classic'
    | '/app/custom'
    | '/app/party'
    | '/app/pro'
    | '/custom/$id'
    | '/custom/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/classic'
    | '/app/custom'
    | '/app/party'
    | '/app/pro'
    | '/custom/$id'
    | '/custom/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CustomIdRoute: typeof CustomIdRoute
  CustomNewRoute: typeof CustomNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/new': {
      id: '/custom/new'
      path: '/custom/new'
      fullPath: '/custom/new'
      preLoaderRoute: typeof CustomNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$id': {
      id: '/custom/$id'
      path: '/custom/$id'
      fullPath: '/custom/$id'
      preLoaderRoute: typeof CustomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pro': {
      id: '/app/pro'
      path: '/pro'
      fullPath: '/app/pro'
      preLoaderRoute: typeof AppProRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/party': {
      id: '/app/party'
      path: '/party'
      fullPath: '/app/party'
      preLoaderRoute: typeof AppPartyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/custom': {
      id: '/app/custom'
      path: '/custom'
      fullPath: '/app/custom'
      preLoaderRoute: typeof AppCustomRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/classic': {
      id: '/app/classic'
      path: '/classic'
      fullPath: '/app/classic'
      preLoaderRoute: typeof AppClassicRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppClassicRoute: typeof AppClassicRoute
  AppCustomRoute: typeof AppCustomRoute
  AppPartyRoute: typeof AppPartyRoute
  AppProRoute: typeof AppProRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClassicRoute: AppClassicRoute,
  AppCustomRoute: AppCustomRoute,
  AppPartyRoute: AppPartyRoute,
  AppProRoute: AppProRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CustomIdRoute: CustomIdRoute,
  CustomNewRoute: CustomNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
